#:schema https://mise.en.dev/schema/mise.json

[settings]
npm.bun = true
npm.package_manager = "bun"
github.credential_command = "gh auth token"

[shell_alias]
cm = "chezmoi"
ms = "mise"
pf = "pitchfork"
bm = "bash ~/.local/scripts/background-noise.sh"
update = "~/.local/scripts/update.sh"

[tools]
# Dotfiles
chezmoi = "latest"

# Shell + dependencies
"aqua:fish-shell/fish-shell" = "latest"
fzf = "latest"
zoxide = "latest"
usage = "latest"
fastfetch = "latest"

# Local development stack
pitchfork = "latest"
postgres = "18"
redis = "8"

# Programming languages
rust = "latest"
go = "latest"
nodejs = "lts"
bun = "latest"
biome = "latest"
python = "latest"
uv = "latest"

# k8s
azure-cli = "latest"
kubelogin = "latest"
azure-kubelogin = "latest"
kubectl = "latest"
k9s = "latest"
helm = "latest"

# cli tools
gh = "latest"
jq = "latest"
bat = "latest"
delta = "latest"
fd = "latest"
ripgrep = "latest"
