#:schema https://mise.en.dev/schema/mise.json

[tools]
# Dotfiles
chezmoi = "latest"

# Shell + dependencies
"aqua:fish-shell/fish-shell" = "latest"
starship = "latest"
fzf = "latest"
zoxide = "latest"
usage = "latest"

# Local development
pitchfork = "latest"
postgres = "18.4"
