#:schema https://mise.en.dev/schema/mise.json

[tools]
# Dotfiles
chezmoi = "latest"

# Shell + dependencies
"aqua:fish-shell/fish-shell" = "latest"
starship = "latest"
fzf = "latest"
zoxide = "latest"

# Process manager
pitchfork = "latest"
usage = "latest"

# State
postgres = "latest"
